// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet_006_OX.proto

#include "Packet_006_OX.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR C_OX_START::C_OX_START(
    ::_pbi::ConstantInitialized) {}
struct C_OX_STARTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_OX_STARTDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_OX_STARTDefaultTypeInternal() {}
  union {
    C_OX_START _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_OX_STARTDefaultTypeInternal _C_OX_START_default_instance_;
PROTOBUF_CONSTEXPR S_OX_START::S_OX_START(
    ::_pbi::ConstantInitialized) {}
struct S_OX_STARTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_OX_STARTDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_OX_STARTDefaultTypeInternal() {}
  union {
    S_OX_START _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_OX_STARTDefaultTypeInternal _S_OX_START_default_instance_;
PROTOBUF_CONSTEXPR S_OX_FINISH::S_OX_FINISH(
    ::_pbi::ConstantInitialized) {}
struct S_OX_FINISHDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_OX_FINISHDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_OX_FINISHDefaultTypeInternal() {}
  union {
    S_OX_FINISH _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_OX_FINISHDefaultTypeInternal _S_OX_FINISH_default_instance_;
PROTOBUF_CONSTEXPR C_OX_GET_HOST::C_OX_GET_HOST(
    ::_pbi::ConstantInitialized) {}
struct C_OX_GET_HOSTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_OX_GET_HOSTDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_OX_GET_HOSTDefaultTypeInternal() {}
  union {
    C_OX_GET_HOST _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_OX_GET_HOSTDefaultTypeInternal _C_OX_GET_HOST_default_instance_;
PROTOBUF_CONSTEXPR S_OX_HOST::S_OX_HOST(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.clientid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct S_OX_HOSTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_OX_HOSTDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_OX_HOSTDefaultTypeInternal() {}
  union {
    S_OX_HOST _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_OX_HOSTDefaultTypeInternal _S_OX_HOST_default_instance_;
PROTOBUF_CONSTEXPR S_OX_ROUND_START::S_OX_ROUND_START(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.mode_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct S_OX_ROUND_STARTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_OX_ROUND_STARTDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_OX_ROUND_STARTDefaultTypeInternal() {}
  union {
    S_OX_ROUND_START _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_OX_ROUND_STARTDefaultTypeInternal _S_OX_ROUND_START_default_instance_;
PROTOBUF_CONSTEXPR S_OX_ROUND_FINISH::S_OX_ROUND_FINISH(
    ::_pbi::ConstantInitialized) {}
struct S_OX_ROUND_FINISHDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_OX_ROUND_FINISHDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_OX_ROUND_FINISHDefaultTypeInternal() {}
  union {
    S_OX_ROUND_FINISH _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_OX_ROUND_FINISHDefaultTypeInternal _S_OX_ROUND_FINISH_default_instance_;
PROTOBUF_CONSTEXPR S_OX_QUIZ::S_OX_QUIZ(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.panel_)*/{}
  , /*decltype(_impl_._panel_cached_byte_size_)*/{0}
  , /*decltype(_impl_.quiz_)*/0
  , /*decltype(_impl_.timetodestory_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct S_OX_QUIZDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_OX_QUIZDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_OX_QUIZDefaultTypeInternal() {}
  union {
    S_OX_QUIZ _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_OX_QUIZDefaultTypeInternal _S_OX_QUIZ_default_instance_;
PROTOBUF_CONSTEXPR S_OX_DESTROY::S_OX_DESTROY(
    ::_pbi::ConstantInitialized) {}
struct S_OX_DESTROYDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_OX_DESTROYDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_OX_DESTROYDefaultTypeInternal() {}
  union {
    S_OX_DESTROY _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_OX_DESTROYDefaultTypeInternal _S_OX_DESTROY_default_instance_;
PROTOBUF_CONSTEXPR S_OX_AWARD::S_OX_AWARD(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.winners_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct S_OX_AWARDDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_OX_AWARDDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_OX_AWARDDefaultTypeInternal() {}
  union {
    S_OX_AWARD _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_OX_AWARDDefaultTypeInternal _S_OX_AWARD_default_instance_;
PROTOBUF_CONSTEXPR C_OX_DIE::C_OX_DIE(
    ::_pbi::ConstantInitialized) {}
struct C_OX_DIEDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_OX_DIEDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_OX_DIEDefaultTypeInternal() {}
  union {
    C_OX_DIE _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_OX_DIEDefaultTypeInternal _C_OX_DIE_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_Packet_5f006_5fOX_2eproto[11];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Packet_5f006_5fOX_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Packet_5f006_5fOX_2eproto = nullptr;

const uint32_t TableStruct_Packet_5f006_5fOX_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::C_OX_START, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_OX_START, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_OX_FINISH, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::C_OX_GET_HOST, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_OX_HOST, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_OX_HOST, _impl_.clientid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_OX_ROUND_START, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_OX_ROUND_START, _impl_.mode_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_OX_ROUND_FINISH, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_OX_QUIZ, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_OX_QUIZ, _impl_.quiz_),
  PROTOBUF_FIELD_OFFSET(::Protocol::S_OX_QUIZ, _impl_.timetodestory_),
  PROTOBUF_FIELD_OFFSET(::Protocol::S_OX_QUIZ, _impl_.panel_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_OX_DESTROY, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_OX_AWARD, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_OX_AWARD, _impl_.winners_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::C_OX_DIE, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::C_OX_START)},
  { 6, -1, -1, sizeof(::Protocol::S_OX_START)},
  { 12, -1, -1, sizeof(::Protocol::S_OX_FINISH)},
  { 18, -1, -1, sizeof(::Protocol::C_OX_GET_HOST)},
  { 24, -1, -1, sizeof(::Protocol::S_OX_HOST)},
  { 31, -1, -1, sizeof(::Protocol::S_OX_ROUND_START)},
  { 38, -1, -1, sizeof(::Protocol::S_OX_ROUND_FINISH)},
  { 44, -1, -1, sizeof(::Protocol::S_OX_QUIZ)},
  { 53, -1, -1, sizeof(::Protocol::S_OX_DESTROY)},
  { 59, -1, -1, sizeof(::Protocol::S_OX_AWARD)},
  { 66, -1, -1, sizeof(::Protocol::C_OX_DIE)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_C_OX_START_default_instance_._instance,
  &::Protocol::_S_OX_START_default_instance_._instance,
  &::Protocol::_S_OX_FINISH_default_instance_._instance,
  &::Protocol::_C_OX_GET_HOST_default_instance_._instance,
  &::Protocol::_S_OX_HOST_default_instance_._instance,
  &::Protocol::_S_OX_ROUND_START_default_instance_._instance,
  &::Protocol::_S_OX_ROUND_FINISH_default_instance_._instance,
  &::Protocol::_S_OX_QUIZ_default_instance_._instance,
  &::Protocol::_S_OX_DESTROY_default_instance_._instance,
  &::Protocol::_S_OX_AWARD_default_instance_._instance,
  &::Protocol::_C_OX_DIE_default_instance_._instance,
};

const char descriptor_table_protodef_Packet_5f006_5fOX_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023Packet_006_OX.proto\022\010Protocol\"\014\n\nC_OX_"
  "START\"\014\n\nS_OX_START\"\r\n\013S_OX_FINISH\"\017\n\rC_"
  "OX_GET_HOST\"\035\n\tS_OX_HOST\022\020\n\010clientId\030\001 \001"
  "(\t\" \n\020S_OX_ROUND_START\022\014\n\004mode\030\001 \001(\t\"\023\n\021"
  "S_OX_ROUND_FINISH\"\?\n\tS_OX_QUIZ\022\014\n\004quiz\030\001"
  " \001(\005\022\025\n\rtimeToDestory\030\003 \001(\005\022\r\n\005panel\030\004 \003"
  "(\005\"\016\n\014S_OX_DESTROY\"\035\n\nS_OX_AWARD\022\017\n\007winn"
  "ers\030\001 \003(\t\"\n\n\010C_OX_DIEb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_Packet_5f006_5fOX_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Packet_5f006_5fOX_2eproto = {
    false, false, 309, descriptor_table_protodef_Packet_5f006_5fOX_2eproto,
    "Packet_006_OX.proto",
    &descriptor_table_Packet_5f006_5fOX_2eproto_once, nullptr, 0, 11,
    schemas, file_default_instances, TableStruct_Packet_5f006_5fOX_2eproto::offsets,
    file_level_metadata_Packet_5f006_5fOX_2eproto, file_level_enum_descriptors_Packet_5f006_5fOX_2eproto,
    file_level_service_descriptors_Packet_5f006_5fOX_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Packet_5f006_5fOX_2eproto_getter() {
  return &descriptor_table_Packet_5f006_5fOX_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Packet_5f006_5fOX_2eproto(&descriptor_table_Packet_5f006_5fOX_2eproto);
namespace Protocol {

// ===================================================================

class C_OX_START::_Internal {
 public:
};

C_OX_START::C_OX_START(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.C_OX_START)
}
C_OX_START::C_OX_START(const C_OX_START& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  C_OX_START* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.C_OX_START)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C_OX_START::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C_OX_START::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata C_OX_START::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Packet_5f006_5fOX_2eproto_getter, &descriptor_table_Packet_5f006_5fOX_2eproto_once,
      file_level_metadata_Packet_5f006_5fOX_2eproto[0]);
}

// ===================================================================

class S_OX_START::_Internal {
 public:
};

S_OX_START::S_OX_START(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.S_OX_START)
}
S_OX_START::S_OX_START(const S_OX_START& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  S_OX_START* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.S_OX_START)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S_OX_START::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S_OX_START::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata S_OX_START::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Packet_5f006_5fOX_2eproto_getter, &descriptor_table_Packet_5f006_5fOX_2eproto_once,
      file_level_metadata_Packet_5f006_5fOX_2eproto[1]);
}

// ===================================================================

class S_OX_FINISH::_Internal {
 public:
};

S_OX_FINISH::S_OX_FINISH(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.S_OX_FINISH)
}
S_OX_FINISH::S_OX_FINISH(const S_OX_FINISH& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  S_OX_FINISH* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.S_OX_FINISH)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S_OX_FINISH::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S_OX_FINISH::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata S_OX_FINISH::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Packet_5f006_5fOX_2eproto_getter, &descriptor_table_Packet_5f006_5fOX_2eproto_once,
      file_level_metadata_Packet_5f006_5fOX_2eproto[2]);
}

// ===================================================================

class C_OX_GET_HOST::_Internal {
 public:
};

C_OX_GET_HOST::C_OX_GET_HOST(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.C_OX_GET_HOST)
}
C_OX_GET_HOST::C_OX_GET_HOST(const C_OX_GET_HOST& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  C_OX_GET_HOST* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.C_OX_GET_HOST)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C_OX_GET_HOST::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C_OX_GET_HOST::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata C_OX_GET_HOST::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Packet_5f006_5fOX_2eproto_getter, &descriptor_table_Packet_5f006_5fOX_2eproto_once,
      file_level_metadata_Packet_5f006_5fOX_2eproto[3]);
}

// ===================================================================

class S_OX_HOST::_Internal {
 public:
};

S_OX_HOST::S_OX_HOST(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.S_OX_HOST)
}
S_OX_HOST::S_OX_HOST(const S_OX_HOST& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  S_OX_HOST* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.clientid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.clientid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.clientid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_clientid().empty()) {
    _this->_impl_.clientid_.Set(from._internal_clientid(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:Protocol.S_OX_HOST)
}

inline void S_OX_HOST::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.clientid_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.clientid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.clientid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

S_OX_HOST::~S_OX_HOST() {
  // @@protoc_insertion_point(destructor:Protocol.S_OX_HOST)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void S_OX_HOST::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.clientid_.Destroy();
}

void S_OX_HOST::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void S_OX_HOST::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.S_OX_HOST)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.clientid_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* S_OX_HOST::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string clientId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_clientid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Protocol.S_OX_HOST.clientId"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* S_OX_HOST::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.S_OX_HOST)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string clientId = 1;
  if (!this->_internal_clientid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_clientid().data(), static_cast<int>(this->_internal_clientid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Protocol.S_OX_HOST.clientId");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_clientid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.S_OX_HOST)
  return target;
}

size_t S_OX_HOST::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.S_OX_HOST)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string clientId = 1;
  if (!this->_internal_clientid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_clientid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S_OX_HOST::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    S_OX_HOST::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S_OX_HOST::GetClassData() const { return &_class_data_; }


void S_OX_HOST::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<S_OX_HOST*>(&to_msg);
  auto& from = static_cast<const S_OX_HOST&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.S_OX_HOST)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_clientid().empty()) {
    _this->_internal_set_clientid(from._internal_clientid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void S_OX_HOST::CopyFrom(const S_OX_HOST& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.S_OX_HOST)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S_OX_HOST::IsInitialized() const {
  return true;
}

void S_OX_HOST::InternalSwap(S_OX_HOST* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.clientid_, lhs_arena,
      &other->_impl_.clientid_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata S_OX_HOST::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Packet_5f006_5fOX_2eproto_getter, &descriptor_table_Packet_5f006_5fOX_2eproto_once,
      file_level_metadata_Packet_5f006_5fOX_2eproto[4]);
}

// ===================================================================

class S_OX_ROUND_START::_Internal {
 public:
};

S_OX_ROUND_START::S_OX_ROUND_START(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.S_OX_ROUND_START)
}
S_OX_ROUND_START::S_OX_ROUND_START(const S_OX_ROUND_START& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  S_OX_ROUND_START* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.mode_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.mode_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.mode_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_mode().empty()) {
    _this->_impl_.mode_.Set(from._internal_mode(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:Protocol.S_OX_ROUND_START)
}

inline void S_OX_ROUND_START::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.mode_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.mode_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.mode_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

S_OX_ROUND_START::~S_OX_ROUND_START() {
  // @@protoc_insertion_point(destructor:Protocol.S_OX_ROUND_START)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void S_OX_ROUND_START::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.mode_.Destroy();
}

void S_OX_ROUND_START::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void S_OX_ROUND_START::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.S_OX_ROUND_START)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.mode_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* S_OX_ROUND_START::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string mode = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_mode();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Protocol.S_OX_ROUND_START.mode"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* S_OX_ROUND_START::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.S_OX_ROUND_START)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string mode = 1;
  if (!this->_internal_mode().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_mode().data(), static_cast<int>(this->_internal_mode().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Protocol.S_OX_ROUND_START.mode");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_mode(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.S_OX_ROUND_START)
  return target;
}

size_t S_OX_ROUND_START::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.S_OX_ROUND_START)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string mode = 1;
  if (!this->_internal_mode().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_mode());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S_OX_ROUND_START::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    S_OX_ROUND_START::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S_OX_ROUND_START::GetClassData() const { return &_class_data_; }


void S_OX_ROUND_START::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<S_OX_ROUND_START*>(&to_msg);
  auto& from = static_cast<const S_OX_ROUND_START&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.S_OX_ROUND_START)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_mode().empty()) {
    _this->_internal_set_mode(from._internal_mode());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void S_OX_ROUND_START::CopyFrom(const S_OX_ROUND_START& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.S_OX_ROUND_START)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S_OX_ROUND_START::IsInitialized() const {
  return true;
}

void S_OX_ROUND_START::InternalSwap(S_OX_ROUND_START* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.mode_, lhs_arena,
      &other->_impl_.mode_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata S_OX_ROUND_START::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Packet_5f006_5fOX_2eproto_getter, &descriptor_table_Packet_5f006_5fOX_2eproto_once,
      file_level_metadata_Packet_5f006_5fOX_2eproto[5]);
}

// ===================================================================

class S_OX_ROUND_FINISH::_Internal {
 public:
};

S_OX_ROUND_FINISH::S_OX_ROUND_FINISH(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.S_OX_ROUND_FINISH)
}
S_OX_ROUND_FINISH::S_OX_ROUND_FINISH(const S_OX_ROUND_FINISH& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  S_OX_ROUND_FINISH* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.S_OX_ROUND_FINISH)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S_OX_ROUND_FINISH::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S_OX_ROUND_FINISH::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata S_OX_ROUND_FINISH::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Packet_5f006_5fOX_2eproto_getter, &descriptor_table_Packet_5f006_5fOX_2eproto_once,
      file_level_metadata_Packet_5f006_5fOX_2eproto[6]);
}

// ===================================================================

class S_OX_QUIZ::_Internal {
 public:
};

S_OX_QUIZ::S_OX_QUIZ(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.S_OX_QUIZ)
}
S_OX_QUIZ::S_OX_QUIZ(const S_OX_QUIZ& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  S_OX_QUIZ* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.panel_){from._impl_.panel_}
    , /*decltype(_impl_._panel_cached_byte_size_)*/{0}
    , decltype(_impl_.quiz_){}
    , decltype(_impl_.timetodestory_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.quiz_, &from._impl_.quiz_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.timetodestory_) -
    reinterpret_cast<char*>(&_impl_.quiz_)) + sizeof(_impl_.timetodestory_));
  // @@protoc_insertion_point(copy_constructor:Protocol.S_OX_QUIZ)
}

inline void S_OX_QUIZ::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.panel_){arena}
    , /*decltype(_impl_._panel_cached_byte_size_)*/{0}
    , decltype(_impl_.quiz_){0}
    , decltype(_impl_.timetodestory_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

S_OX_QUIZ::~S_OX_QUIZ() {
  // @@protoc_insertion_point(destructor:Protocol.S_OX_QUIZ)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void S_OX_QUIZ::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.panel_.~RepeatedField();
}

void S_OX_QUIZ::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void S_OX_QUIZ::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.S_OX_QUIZ)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.panel_.Clear();
  ::memset(&_impl_.quiz_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.timetodestory_) -
      reinterpret_cast<char*>(&_impl_.quiz_)) + sizeof(_impl_.timetodestory_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* S_OX_QUIZ::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 quiz = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.quiz_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 timeToDestory = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.timetodestory_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated int32 panel = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_panel(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 32) {
          _internal_add_panel(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* S_OX_QUIZ::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.S_OX_QUIZ)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 quiz = 1;
  if (this->_internal_quiz() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_quiz(), target);
  }

  // int32 timeToDestory = 3;
  if (this->_internal_timetodestory() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_timetodestory(), target);
  }

  // repeated int32 panel = 4;
  {
    int byte_size = _impl_._panel_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          4, _internal_panel(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.S_OX_QUIZ)
  return target;
}

size_t S_OX_QUIZ::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.S_OX_QUIZ)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 panel = 4;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.panel_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._panel_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // int32 quiz = 1;
  if (this->_internal_quiz() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_quiz());
  }

  // int32 timeToDestory = 3;
  if (this->_internal_timetodestory() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_timetodestory());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S_OX_QUIZ::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    S_OX_QUIZ::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S_OX_QUIZ::GetClassData() const { return &_class_data_; }


void S_OX_QUIZ::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<S_OX_QUIZ*>(&to_msg);
  auto& from = static_cast<const S_OX_QUIZ&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.S_OX_QUIZ)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.panel_.MergeFrom(from._impl_.panel_);
  if (from._internal_quiz() != 0) {
    _this->_internal_set_quiz(from._internal_quiz());
  }
  if (from._internal_timetodestory() != 0) {
    _this->_internal_set_timetodestory(from._internal_timetodestory());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void S_OX_QUIZ::CopyFrom(const S_OX_QUIZ& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.S_OX_QUIZ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S_OX_QUIZ::IsInitialized() const {
  return true;
}

void S_OX_QUIZ::InternalSwap(S_OX_QUIZ* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.panel_.InternalSwap(&other->_impl_.panel_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(S_OX_QUIZ, _impl_.timetodestory_)
      + sizeof(S_OX_QUIZ::_impl_.timetodestory_)
      - PROTOBUF_FIELD_OFFSET(S_OX_QUIZ, _impl_.quiz_)>(
          reinterpret_cast<char*>(&_impl_.quiz_),
          reinterpret_cast<char*>(&other->_impl_.quiz_));
}

::PROTOBUF_NAMESPACE_ID::Metadata S_OX_QUIZ::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Packet_5f006_5fOX_2eproto_getter, &descriptor_table_Packet_5f006_5fOX_2eproto_once,
      file_level_metadata_Packet_5f006_5fOX_2eproto[7]);
}

// ===================================================================

class S_OX_DESTROY::_Internal {
 public:
};

S_OX_DESTROY::S_OX_DESTROY(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.S_OX_DESTROY)
}
S_OX_DESTROY::S_OX_DESTROY(const S_OX_DESTROY& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  S_OX_DESTROY* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.S_OX_DESTROY)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S_OX_DESTROY::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S_OX_DESTROY::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata S_OX_DESTROY::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Packet_5f006_5fOX_2eproto_getter, &descriptor_table_Packet_5f006_5fOX_2eproto_once,
      file_level_metadata_Packet_5f006_5fOX_2eproto[8]);
}

// ===================================================================

class S_OX_AWARD::_Internal {
 public:
};

S_OX_AWARD::S_OX_AWARD(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.S_OX_AWARD)
}
S_OX_AWARD::S_OX_AWARD(const S_OX_AWARD& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  S_OX_AWARD* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.winners_){from._impl_.winners_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.S_OX_AWARD)
}

inline void S_OX_AWARD::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.winners_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

S_OX_AWARD::~S_OX_AWARD() {
  // @@protoc_insertion_point(destructor:Protocol.S_OX_AWARD)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void S_OX_AWARD::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.winners_.~RepeatedPtrField();
}

void S_OX_AWARD::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void S_OX_AWARD::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.S_OX_AWARD)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.winners_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* S_OX_AWARD::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string winners = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_winners();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "Protocol.S_OX_AWARD.winners"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* S_OX_AWARD::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.S_OX_AWARD)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string winners = 1;
  for (int i = 0, n = this->_internal_winners_size(); i < n; i++) {
    const auto& s = this->_internal_winners(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Protocol.S_OX_AWARD.winners");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.S_OX_AWARD)
  return target;
}

size_t S_OX_AWARD::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.S_OX_AWARD)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string winners = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.winners_.size());
  for (int i = 0, n = _impl_.winners_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.winners_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S_OX_AWARD::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    S_OX_AWARD::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S_OX_AWARD::GetClassData() const { return &_class_data_; }


void S_OX_AWARD::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<S_OX_AWARD*>(&to_msg);
  auto& from = static_cast<const S_OX_AWARD&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.S_OX_AWARD)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.winners_.MergeFrom(from._impl_.winners_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void S_OX_AWARD::CopyFrom(const S_OX_AWARD& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.S_OX_AWARD)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S_OX_AWARD::IsInitialized() const {
  return true;
}

void S_OX_AWARD::InternalSwap(S_OX_AWARD* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.winners_.InternalSwap(&other->_impl_.winners_);
}

::PROTOBUF_NAMESPACE_ID::Metadata S_OX_AWARD::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Packet_5f006_5fOX_2eproto_getter, &descriptor_table_Packet_5f006_5fOX_2eproto_once,
      file_level_metadata_Packet_5f006_5fOX_2eproto[9]);
}

// ===================================================================

class C_OX_DIE::_Internal {
 public:
};

C_OX_DIE::C_OX_DIE(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.C_OX_DIE)
}
C_OX_DIE::C_OX_DIE(const C_OX_DIE& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  C_OX_DIE* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.C_OX_DIE)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C_OX_DIE::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C_OX_DIE::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata C_OX_DIE::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Packet_5f006_5fOX_2eproto_getter, &descriptor_table_Packet_5f006_5fOX_2eproto_once,
      file_level_metadata_Packet_5f006_5fOX_2eproto[10]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::C_OX_START*
Arena::CreateMaybeMessage< ::Protocol::C_OX_START >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::C_OX_START >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S_OX_START*
Arena::CreateMaybeMessage< ::Protocol::S_OX_START >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S_OX_START >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S_OX_FINISH*
Arena::CreateMaybeMessage< ::Protocol::S_OX_FINISH >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S_OX_FINISH >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::C_OX_GET_HOST*
Arena::CreateMaybeMessage< ::Protocol::C_OX_GET_HOST >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::C_OX_GET_HOST >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S_OX_HOST*
Arena::CreateMaybeMessage< ::Protocol::S_OX_HOST >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S_OX_HOST >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S_OX_ROUND_START*
Arena::CreateMaybeMessage< ::Protocol::S_OX_ROUND_START >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S_OX_ROUND_START >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S_OX_ROUND_FINISH*
Arena::CreateMaybeMessage< ::Protocol::S_OX_ROUND_FINISH >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S_OX_ROUND_FINISH >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S_OX_QUIZ*
Arena::CreateMaybeMessage< ::Protocol::S_OX_QUIZ >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S_OX_QUIZ >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S_OX_DESTROY*
Arena::CreateMaybeMessage< ::Protocol::S_OX_DESTROY >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S_OX_DESTROY >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S_OX_AWARD*
Arena::CreateMaybeMessage< ::Protocol::S_OX_AWARD >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S_OX_AWARD >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::C_OX_DIE*
Arena::CreateMaybeMessage< ::Protocol::C_OX_DIE >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::C_OX_DIE >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
